mkdocstrings/pytkdocs

- src/pytkdocs/parsers/docstrings.py
- tests/test_parsers/test_docstrings.py
The inspect library stores the `*args` and `**kwargs` parameters under the keys `args` and `kwargs` respectively. This behavior caused a key error when looking for the parameters using the  `*args` and `**kwargs` keys.
Issue: https://github.com/pawamoy/pytkdocs/issues/20
> Fix parsing of *args and **kwargs

- src/pytkdocs/objects.py
- tests/fixtures/test_namespace/subspace/__init__.py
- tests/test_loader.py
This fixes an issue finding the relative path when the root package is a namespace package. This is likely to break if the namespace package is nested in the module like `my_package.plugins` and you want to document something that lives in that plugins namespace.
> Fix unable to find root namespace

- pyproject.toml
- src/pytkdocs/loader.py
- tests/fixtures/dataclass.py
- tests/fixtures/pydantic.py
- tests/test_loader.py
This PR adds support for parsing dataclass annotations and PyDantic fields as attributes of a class.
> Add dataclass and pydantic support

- docs/developers/test_suite/test_parsers/test_docstrings.md
- docs/developers/test_suite/test_parsers/test_docstrings/test_google.md
- docs/reference/parsers/docstrings.md
- docs/reference/parsers/docstrings/__init__.md
- docs/reference/parsers/docstrings/base.md
- docs/reference/parsers/docstrings/google.md
- mkdocs.yml
- src/pytkdocs/parsers/docstrings/base.py
- src/pytkdocs/parsers/docstrings/google.py
- src/pytkdocs/serializer.py
- tests/test_parsers/test_docstrings/test_google.py
This PR is to support the examples section.
In progress...
Issue #8 and PR https://github.com/pawamoy/mkdocstrings/pull/112
> Support examples section

- src/pytkdocs/loader.py
- tests/fixtures/first_line_class_docstring.py
- tests/test_loader.py
Let me know if there's a better place to put the test (or if you'd rather leave out the test)
> fix #54: Use inspect.cleandoc for stripping docstring whitespace

- src/pytkdocs/loader.py
- tests/fixtures/dataclass.py
- tests/test_loader.py
Ran into this when applying mkdocstrings to a real life project. I won't pretend that there was a legitimate reason to use an empty dataclass in my code, but thought it was worth preventing the crash 🙈
> fix: Prevent crash in case of empty dataclasses

- pyproject.toml
- src/pytkdocs/loader.py
- tests/fixtures/marshmallow.py
- tests/fixtures/parsing/attributes.py
- tests/test_loader.py
- tests/test_parsers/test_attributes.py
Basic support for marshmallow schemas https://marshmallow.readthedocs.io/en/stable/
It would be nice if we could override the default renderer for these types of classes to show a table instead of the header style renderer?
> add initial marshmallow support

- .github/workflows/ci.yml
I spent some time to get the CI pipeline into a better state. 
There is one issue that I can't explain. I had gotten [everything working](https://github.com/plannigan/pytkdocs/actions/runs/300546337). However, after I squashed all the debugging commits into a single clean commit, [installing the dependencies on Windows](https://github.com/plannigan/pytkdocs/runs/1238411387?check_suite_focus=true) always hangs instead of completing. If this persists, maybe running CI on Windows can be disabled for now.
Changes:
* Use `setup.sh` directly instead of `make` so it will only setup project for the python version of CI step. On Windows, [poetry wasn't finding the correct python executable](https://github.com/plannigan/pytkdocs/runs/1238115874?check_suite_focus=true#step:5:86). However, …
> chore: Update CI workflow into a better state

- tests/test_cli.py
In the normal flow, there is no difference. However, running `pytest` directly with arguments would cause those arguments to be used by the test case.
> Explicitly test with no arguments

- src/pytkdocs/loader.py
I was attempting to use `mkdocstrings` with some Python library I maintain, only to find it failed because one of the classes referred to itself in one of its members. I'm not sure if this fix is ideal (since it omits the member entirely rather than including it but making it clear that there is a self-reference involved; and it doesn't deal with with non-local recursion).
What are your thoughts?
> fix: Avoid recursion if a class has a reference to itself.

- pyproject.toml
A new version of `dataclasses` was [released last month](https://pypi.org/project/dataclasses/#history).
This should resolve the issue that caused pawamoy/mkdocstrings#198 to fail. I looked at `poetry`'s extra verbose install output:
```
...
1: fact: black (20.8b1) depends on dataclasses (>=0.6)
1: selecting black (20.8b1)
1: derived: dataclasses (>=0.6)
...
1: selecting dataclasses (0.8)
...
1: fact: pytkdocs (0.10.0) depends on dataclasses (>=0.7,<0.8)
1: fact: pytkdocs (0.10.0) depends on typing-extensions (>=3.7.4.3,<4.0.0.0)
1: derived: not pytkdocs (0.10.0)
1: selecting pytkdocs (0.9.0)
...
```
`dataclasses` doesn't show up anywhere else in the file. So based on that, it would seem like `poetry` should be able to backtrack and select an older version of `dataclasses`, but it …
> fix: Allow newer version of dataclasses backport

- .github/workflows/ci.yml
- CREDITS.md
- README.md
- pyproject.toml
- src/pytkdocs/parsers/docstrings/__init__.py
- src/pytkdocs/parsers/docstrings/numpy.py
- tests/test_parsers/test_docstrings/test_numpy.py
This is an initial stab at supporting numpy style docstrings. The `docstring_parser` library is used, therefore not all errors are caught but I still think it's useful especially since the objective is to enable mkdocs to automatically document functions with the `mkdocstrings` plugin. 
Speaking of `mkdocstrings`, I couldn't quite figure out how to switch (package-wide) to a different docstring style from the [documentation]( https://pawamoy.github.io/mkdocstrings/usage/ ) 🤔 .
Fixes #7
> feat: Add support for Numpy docstrings

- src/pytkdocs/loader.py
- tests/fixtures/pydantic.py
- tests/test_loader.py
Fixes #94 
Note that I have tested this for these types
List, Set, Tuple, Union
Update on why Optional isn't working: [This explains it](https://github.com/samuelcolvin/pydantic/blob/b7a8ef25c667b5dd4c4cd0b109c6625d1a57139a/pydantic/fields.py#L517-L521)
> Fix pydantic field documentation for List/Set/Tuple

- CONTRIBUTING.md
- pyproject.toml
- src/pytkdocs/objects.py
- tests/fixtures/dataclass.py
This should fix the issue of dataclasses having duplicate attributes when these have defaults. This occurs because attributes with defaults are interpreted differently by Python (as they have a default, they already "exist" in the "regular" class). 
The solution implemented here first checks if the argument is already present in `self.arguments` (comparison by name). If it is, it replaces the old argument (as the new one has the `dataclass_field` property set).
> Bugfix duplicate dataclass attributes

- pyproject.toml
- src/pytkdocs/loader.py
- tests/fixtures/django.py
- tests/test_loader.py
That's just basic support for now - supports blank and required attributes.
Looks like it works for my old university project (sorry for Polish verbose_names ;)
References: #39.
> Add support for Django models

- src/pytkdocs/loader.py
- tests/fixtures/method_descriptor.py
- tests/test_loader.py
Hi,
I'm trying to add support for python methods created using [pyo3](https://pyo3.rs/). These methods are "built-in" methods, however they can still expose the `__doc__` attribute and a function signature via `__text_signature__`.
The current implementation detects `method_descriptors` (which is what most native functions end up as), and serializes them as regular methods (since from a caller point of view, they act the same). If the user doesn't provide the `__text_signature__` attribute, `inspect.signature` will error out, so I made it optional, as I still think it would be useful to have the docstring in the resulting documentation if it exists. 
Please let me know if this is the right direction for this approach. There are other modifications coming to `mkdocstrings` too, as it …
> [FEATURE] Allow method_descriptors to be serialized as methods

- src/pytkdocs/parsers/docstrings/base.py
- src/pytkdocs/parsers/docstrings/google.py
- tests/test_parsers/test_docstrings/test_google.py
Add support for "Keyword Args" and "Keyword Arguments" sections for
Google-style docstrings.
Closes #88.
> feat: Support "Keyword Args" sections for G-style

- src/pytkdocs/loader.py
- src/pytkdocs/objects.py
- src/pytkdocs/serializer.py
- tests/test_loader.py
Part of resolving https://github.com/mkdocstrings/mkdocstrings/issues/269
> Include base classes in output

- src/pytkdocs/loader.py
- tests/fixtures/decorated_function.py
- tests/test_loader.py
Issue mkdocstrings#162: https://github.com/mkdocstrings/mkdocstrings/issues/162
> fix: Fix getting parent module of decorated functions

- src/pytkdocs/loader.py
- tests/test_loader.py
This is usually not actionable: the user cannot fix the warning.
Issue #111: https://github.com/mkdocstrings/pytkdocs/issues/111
> fix: Skip 'could not read code' errors for special methods

- README.md
- src/pytkdocs/loader.py
pytkdocs will eventually be replaced by griffe.
It means maintenance plans for pytkdocs are dropped
as it will not evolve a lot until griffe is used.
> refactor: Remove warning about new path style option

- src/pytkdocs/loader.py
The full context was not being passed to `parse_docstring`. This was not allowing `Class` signatures to be passed down for extra context and instead would only rely on the class docstring itself.
> pass context to parse_docstring

- src/pytkdocs/loader.py
Adds `Source` when instantiating `Class` in `get_class_documentation`
This [feature](https://github.com/mkdocstrings/mkdocstrings/pull/274) in `mkdocstrings` allowed for sorting of members on render via `members_order: source`. 
It relies on `source.line_start` existing on the objects that are being sorted. 
For  example a file of Classes will now render correctly with respect to the `members_order: source`
> fix: add source to class object

- src/pytkdocs/loader.py
Here are added features:
- support for `help_text` parameter of django model field
- casting docstring to string type, which solves the problem of serializing `Proxy` objects in case of lazy translation
This is the final result with and without `help_text`:
this closes #127
> Add support for help_text field parameter as docstring for django model fields.

- README.md
- src/pytkdocs/parsers/docstrings/google.py
- src/pytkdocs/parsers/docstrings/numpy.py
- tests/test_parsers/test_docstrings/test_google.py
- tests/test_parsers/test_docstrings/test_numpy.py
Related to: https://github.com/mkdocstrings/mkdocstrings/issues/386
I've decided to start the work on the above issue starting from the legacy parser. Please take a look and see if I'm going in the right direction or if I've missed anything crucial.
* Feat: Implemented the functionality of removal of `# doctest:` and `<BLANKLINE>` via regex; in *both* cases where 1. line starts with `>>>` and 2. line is "in a code example block". This is activated via the new `trim_doctest_flags` parameter / option.
* As mentioned in the parent issue, I have set the default behaviour of `trim_doctest_flags` to be True. To keep consistent with Sphinx.
* Only implemented for Google and Numpy for now. I'm not sure how to do it for Rst, it doesn't seem like Rst is parsing examples explicitly (or at all?). If …
> feat: Add `trim_doctest_flag` to google and numpy parsers
